{{- if .Values.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "step-certificates.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
  {{- with .Values.networkpolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: {{ include "step-certificates.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}
